workflows:
  ios-ipa:
    name: iOS IPA Build

    integrations:
      app_store_connect: "Zadana Codemagic API Key"

    environment:
      flutter: stable
      xcode: latest
      groups:
        - app_store_connect

      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.zadana.delivery

      vars:
        BUNDLE_ID: com.zadana.delivery

    scripts:
      - flutter pub get
      - dart run build_runner build --delete-conflicting-outputs
      - keychain initialize
      - xcode-project use-profiles
      - flutter build ipa --release --dart-define=DRIVER_ONESIGNAL_APP_ID=$DRIVER_ONESIGNAL_APP_ID

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: false