import 'package:google_maps_flutter/google_maps_flutter.dart';
import 'package:zadana_delivery/features/driver_home/presentation/widgets/driver_order_preview.dart';

const driverHomeInitialCameraPosition = CameraPosition(
  target: LatLng(30.0444, 31.2357),
  zoom: 11.8,
);

const driverHomeMockDriverLocation = LatLng(30.0742, 31.2920);

const driverHomeMockOrders = <DriverOrderPreview>[
  DriverOrderPreview(
    id: '1234',
    title: 'طلب #1234',
    vendorName: 'سلة جرين ماركت',
    pickupAddress: '12 طريق الملك فيصل، مدينة نصر',
    pickupLatitude: 30.0724,
    pickupLongitude: 31.2872,
    customerName: 'منى عادل',
    deliveryAddress: '32 شارع عباس العقاد، مدينة نصر',
    deliveryLatitude: 30.0609,
    deliveryLongitude: 31.3124,
    distance: '3.2 كم',
    eta: '15 دقيقة',
    payout: '85 ريال',
    vendorInitials: 'جس',
    customerInitials: 'مع',
    packageNote: 'خضار طازة، خليك حريص في النقل وما تحطش الطلب تحت أي وزن.',
    orderItems: [
      DriverOrderItemPreview(name: 'طماطم', quantity: 3),
      DriverOrderItemPreview(name: 'خيار', quantity: 2),
      DriverOrderItemPreview(name: 'بطاطس', quantity: 2),
      DriverOrderItemPreview(name: 'فلفل ألوان', quantity: 1),
    ],
  ),
  DriverOrderPreview(
    id: '1235',
    title: 'طلب #1235',
    vendorName: 'أسواق الدانة',
    pickupAddress: 'شارع التخصصي، الرياض',
    pickupLatitude: 30.0219,
    pickupLongitude: 31.2105,
    customerName: 'ناصر',
    deliveryAddress: 'حي الياسمين، الرياض',
    deliveryLatitude: 30.0398,
    deliveryLongitude: 31.2336,
    distance: '4.1 كم',
    eta: '18 دقيقة',
    payout: '92 ريال',
    vendorInitials: 'أد',
    customerInitials: 'ن',
    packageNote: 'خضروات يومية، تأكد من عدد الأكياس قبل الخروج.',
    orderItems: [
      DriverOrderItemPreview(name: 'خيار', quantity: 4),
      DriverOrderItemPreview(name: 'طماطم', quantity: 5),
      DriverOrderItemPreview(name: 'جزر', quantity: 2),
      DriverOrderItemPreview(name: 'كوسة', quantity: 3),
    ],
    countdownSeconds: 75,
  ),
  DriverOrderPreview(
    id: '1236',
    title: 'طلب #1236',
    vendorName: 'مخبز السراة',
    pickupAddress: 'حي الندى، الرياض',
    pickupLatitude: 30.1236,
    pickupLongitude: 31.3314,
    customerName: 'سعد',
    deliveryAddress: 'حي النرجس، الرياض',
    deliveryLatitude: 30.1094,
    deliveryLongitude: 31.3482,
    distance: '2.8 كم',
    eta: '12 دقيقة',
    payout: '64 ريال',
    vendorInitials: 'مس',
    customerInitials: 'س',
    packageNote: 'خضار للطبخ، حافظ على الأكياس مرتبة.',
    orderItems: [
      DriverOrderItemPreview(name: 'بطاطس', quantity: 4),
      DriverOrderItemPreview(name: 'بصل', quantity: 3),
      DriverOrderItemPreview(name: 'ثوم', quantity: 2),
    ],
    countdownSeconds: 90,
  ),
  DriverOrderPreview(
    id: '1237',
    title: 'طلب #1237',
    vendorName: 'كافيه بين',
    pickupAddress: 'شارع الطيران، مصر الجديدة',
    pickupLatitude: 30.0912,
    pickupLongitude: 31.3174,
    customerName: 'أحمد',
    deliveryAddress: 'شارع النزهة، مصر الجديدة',
    deliveryLatitude: 30.0986,
    deliveryLongitude: 31.3328,
    distance: '3.6 كم',
    eta: '14 دقيقة',
    payout: '78 ريال',
    vendorInitials: 'كب',
    customerInitials: 'أ',
    packageNote: 'خضروات مختارة، حافظ على الطلب ثابت أثناء التوصيل.',
    orderItems: [
      DriverOrderItemPreview(name: 'فلفل أخضر', quantity: 3),
      DriverOrderItemPreview(name: 'باذنجان', quantity: 2),
      DriverOrderItemPreview(name: 'كوسة', quantity: 2),
    ],
    countdownSeconds: 80,
  ),
  DriverOrderPreview(
    id: '1238',
    title: 'طلب #1238',
    vendorName: 'صيدلية الشفاء',
    pickupAddress: 'شارع جابر بن حيان، الدقي',
    pickupLatitude: 30.0508,
    pickupLongitude: 31.2001,
    customerName: 'ليلى',
    deliveryAddress: 'شارع البطاويني، الدقي',
    deliveryLatitude: 30.0427,
    deliveryLongitude: 31.2096,
    distance: '2.1 كم',
    eta: '10 دقيقة',
    payout: '56 ريال',
    vendorInitials: 'صش',
    customerInitials: 'ل',
    packageNote: 'طلب خضار خفيف، راجع الأصناف بعناية قبل الاستلام.',
    orderItems: [
      DriverOrderItemPreview(name: 'ليمون', quantity: 2),
      DriverOrderItemPreview(name: 'نعناع', quantity: 3),
      DriverOrderItemPreview(name: 'خيار', quantity: 2),
    ],
    countdownSeconds: 70,
  ),
  DriverOrderPreview(
    id: '1239',
    title: 'طلب #1239',
    vendorName: 'سوبر ماركت الخير',
    pickupAddress: 'شارع الجيش، شبرا',
    pickupLatitude: 30.0874,
    pickupLongitude: 31.2468,
    customerName: 'خالد',
    deliveryAddress: 'شارع روض الفرج، شبرا',
    deliveryLatitude: 30.1018,
    deliveryLongitude: 31.2511,
    distance: '5.4 كم',
    eta: '21 دقيقة',
    payout: '108 ريال',
    vendorInitials: 'سخ',
    customerInitials: 'خ',
    packageNote: 'طلب خضار عائلي كبير، تأكد من كل الأكياس والفاتورة.',
    orderItems: [
      DriverOrderItemPreview(name: 'طماطم', quantity: 4),
      DriverOrderItemPreview(name: 'خيار', quantity: 3),
      DriverOrderItemPreview(name: 'بطاطس', quantity: 5),
      DriverOrderItemPreview(name: 'بصل', quantity: 3),
      DriverOrderItemPreview(name: 'جزر', quantity: 2),
    ],
    countdownSeconds: 95,
  ),
  DriverOrderPreview(
    id: '1240',
    title: 'طلب #1240',
    vendorName: 'مطعم زعتر',
    pickupAddress: 'شارع المكرم عبيد، مدينة نصر',
    pickupLatitude: 30.0615,
    pickupLongitude: 31.3365,
    customerName: 'رانيا',
    deliveryAddress: 'حي السابع، مدينة نصر',
    deliveryLatitude: 30.0568,
    deliveryLongitude: 31.3492,
    distance: '3.9 كم',
    eta: '16 دقيقة',
    payout: '88 ريال',
    vendorInitials: 'مز',
    customerInitials: 'ر',
    packageNote: 'خضروات طازة، حاول توصل بسرعة للحفاظ على الجودة.',
    orderItems: [
      DriverOrderItemPreview(name: 'خس', quantity: 1),
      DriverOrderItemPreview(name: 'جرجير', quantity: 2),
      DriverOrderItemPreview(name: 'طماطم شيري', quantity: 2),
    ],
    countdownSeconds: 85,
  ),
  DriverOrderPreview(
    id: '1241',
    title: 'طلب #1241',
    vendorName: 'ملحمة المها',
    pickupAddress: 'شارع تسعين، التجمع',
    pickupLatitude: 30.0087,
    pickupLongitude: 31.4321,
    customerName: 'عمر',
    deliveryAddress: 'اللوتس الجنوبي، التجمع',
    deliveryLatitude: 30.0162,
    deliveryLongitude: 31.4465,
    distance: '6.2 كم',
    eta: '24 دقيقة',
    payout: '124 ريال',
    vendorInitials: 'مه',
    customerInitials: 'ع',
    packageNote: 'خضار مطبخ، يفضل تسليمها مباشرة بدون تأخير.',
    orderItems: [
      DriverOrderItemPreview(name: 'ملوخية', quantity: 2),
      DriverOrderItemPreview(name: 'سبانخ', quantity: 2),
      DriverOrderItemPreview(name: 'كزبرة', quantity: 3),
    ],
    countdownSeconds: 100,
  ),
  DriverOrderPreview(
    id: '1242',
    title: 'طلب #1242',
    vendorName: 'مخبوزات الدار',
    pickupAddress: 'شارع 9، المعادي',
    pickupLatitude: 29.9618,
    pickupLongitude: 31.2575,
    customerName: 'نور',
    deliveryAddress: 'زهراء المعادي',
    deliveryLatitude: 29.9736,
    deliveryLongitude: 31.2749,
    distance: '4.7 كم',
    eta: '19 دقيقة',
    payout: '90 ريال',
    vendorInitials: 'مد',
    customerInitials: 'ن',
    packageNote: 'خضروات وفاكهة خفيفة، خليك حريص على شكل الأكياس.',
    orderItems: [
      DriverOrderItemPreview(name: 'تفاح', quantity: 4),
      DriverOrderItemPreview(name: 'موز', quantity: 3),
      DriverOrderItemPreview(name: 'خيار', quantity: 2),
    ],
    countdownSeconds: 88,
  ),
];
